language: node_js
node_js: node
cache: npm
dist: xenial
addons:
  ssh_known_hosts: ssh-oncletom.alwaysdata.net

before_install:
- npm config set production false

before_deploy:
- openssl aes-256-cbc -K $encrypted_a47c168ad38c_key -iv $encrypted_a47c168ad38c_iv -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa
- cp -r  source/.well-known public/.well-known

env:
- NODE_ENV=production

deploy:
- provider: script
  edge: true
  script: npm run deploy
  on:
    branch: master
- provider: script
  edge: true
  script: npm run index-content
  on:
    branch: master
