on:
  rss:
    url: https://thom4.net/feed/

jobs:
  # see https://github.com/actionsflow/actionsflow-workflow-default
  # and https://actionsflow.github.io/docs/workflow/
  request:
    name: Publish on Mastodon
    runs-on: ubuntu-latest
    steps:
      - name: Publish on Mastodon
        uses: actionsflow/axios@v1
        # see https://github.com/actionsflow/axios
        with:
          url: https://diaspodon.fr/api/v1/statuses
          method: POST
          bearer-token: ${{ secrets.MASTODON_PUBLISHING_TOKEN }}
          # see https://docs.joinmastodon.org/methods/statuses/
          # and https://docs.joinmastodon.org/client/intro/#parameters
          data: '{ "status": "<<<${{ on.rss.outputs.title }}>>> 🗞 ${{ on.rss.outputs.link }}" }'
