# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: alwaysdata
      url: https://oncletom.io

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js v16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.SSH_DEPLOY_KEY }}"
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - run: npm ci
    - run: npm run build
      env:
        NODE_ENV: production

    - run: npm run deploy
    - run: npm run index-content
      env:
        HEXO_ALGOLIA_INDEXING_KEY: "${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}"
